### ISSUE TITLE
Default User and Password for Binaries

### ISSUE THREAD

**Issue by mayermakes** [ESP32DE/Boot-Linux-ESP32S3-Playground#11]
Hi , i just got the Olimex esp32-S3 image to boot, but I can´t log in. The usual root and empty password do not work/ other usual combinations did not work
It would be helpfull to include the default login in the docs next to the binaries or in the Readme.
thanks.

TL:DR: Whats the default User and password? please ad it to the docs.

**Comment by mayermakes** [comment]
tried out a lot of combinations and  root /olimex did work in the end. 
but yeah this should be noted somewhere in the docs.

**Comment by ESP32DE** [comment]
> .. this should be noted somewhere in the docs.
it's - moretimes :) #RTFM 

https://github.com/ESP32DE/Boot-Linux-ESP32S3-Playground/issues/5#issuecomment-1660477445

https://github.com/ESP32DE/Boot-Linux-ESP32S3-Playground/issues/9

https://github.com/ESP32DE/Boot-Linux-ESP32S3-Playground/issues/5

![image](https://github.com/ESP32DE/Boot-Linux-ESP32S3-Playground/assets/16070445/faaf62f0-b062-48cf-856c-9c9eeafd8817)

**Comment by ESP32DE** [comment]
> thanks I never had such a popup show up..also never hovered over it.

you can also [click it](https://github.com/ESP32DE/Boot-Linux-ESP32S3-Playground/commit/ac0b18f2604a9f82f898bd28d0424cd21e8f51e7) :)  and you get more the more background what you all can do with it.
you checked the micropython port in there ? the blinky ? the pwm ... the spi ... the i2c ... the oled screen .... there are many easter eggs
