### ISSUE TITLE
I made a flash tool let me know if you want to merge it.

### ISSUE THREAD

**Issue by mayermakes** [ESP32DE/Boot-Linux-ESP32S3-Playground#12]
Hi, I wrapped the flash commands to get the binaries on the S3 into a little linux shell script so the process is a bit easier.
works for my own Sudosom-S3 board (Cm4 style) but should work on any S3 in theory.
https://github.com/mayermakes/Sudoflash
let me know if you want to merge it  to the Playground

**Comment by ESP32DE** [comment]
> Hi, I wrapped the flash commands to get the binaries on the S3 into a little linux shell script so the process is a bit easier. works for my own Sudosom-S3 board (Cm4 style) but should work on any S3 in theory. https://github.com/mayermakes/Sudoflash let me know if you want to merge it to the Playground

note, there is already a [flashtool for several os](https://github.com/espressif/esptool) and a nice gui [flashtool for win](https://www.espressif.com/sites/default/files/tools/flash_download_tool_3.9.5.zip)
you can also combine all to one and flash only one binary to 0x0.
check the [espressif tools](https://www.espressif.com/en/support/download/other-tools) :) 

jfyi you can fork this playground repo and add your tools for your Sudosom-S3 in a folder example
