### ISSUE TITLE
root password for bin images

### ISSUE THREAD

**Issue by morgana2313** [ESP32DE/Boot-Linux-ESP32S3-Playground#5]
Hello Rudi,

Very cool! I just booted the [ESP32S3N8R8BlinkyGPIO2.bin](https://github.com/ESP32DE/Boot-Linux-ESP32S3-Playground/blob/main/bins/S3/ESP32S3N8R8BlinkyGPIO2.bin) on a [Wemos Lolin S3](https://www.wemos.cc/en/latest/s3/s3.html), and it booted like a charm.

Could you share  the root password for the bin images so I can acutally log on?

Enjoy, Jasper

**Comment by morgana2313** [comment]
I guessed it: `eMbeddedHome`.

**Comment by avirus** [comment]
password for olimexS3WROOM_N8qdR8ot.bin image is oilmex

**Comment by ESP32DE** [comment]
> password for olimexS3WROOM_N8qdR8ot.bin image is oilmex

nah... it's "olimex" 
;-)
and for m5stack ...?
guess :)

**Comment by navigamer123** [comment]
> I guessed it: `eMbeddedHome`.

sorry for asking but what is the user
