### ISSUE TITLE
Some Questions / Requests

### ISSUE THREAD

**Issue by vslinuxdotnet** [ESP32DE/Boot-Linux-ESP32S3-Playground#6]
Hello,
I already compile and test it with wifi support, but I have some questions:

Is possible to run Linux kernel with both CPU's ?
Why CPU is running at 160mhz if 240mhz was available ?
Is possible to add SDCARD as media to boot kernel and rootfs with RW support ?
Is possible to add I2C,SPI and GPIO's ?

Thank you,
VS

**Comment by ESP32DE** [comment]
> Hello, I already compile and test it with wifi support, but I have some questions:
> 

Hi - great so your wifi s3 linux is working :)

> Is possible to run Linux kernel with both CPU's ? 

without the wifi FreeRTOS on Wifi CPU ?
in the wifi s3 linux we use all 2 CPU's
run Linux and FreeRTOS  parallel cores which share some hardware (e.g. the interrupt matrix) 
IDF code was (example) [expanded get some modifications](https://github.com/jcmvbkbc/esp-hosted/blob/d5e98ed61cd776bedf3dea5af45d9c58da8e58db/esp_hosted_ng/esp/esp_driver/network_adapter/main/shmem_slave_api.c#L45-L460).

Having SMP ? 
- implementation of different IPI mechanism 
- making IPI configurable.
- ..

> Why CPU is running at 160mhz if 240mhz was available ?

cause it is set to 160 MHz usually as standard
you can [change to 80 MHz as well and 240 MHz](https://esp32.com/viewtopic.php?f=17&t=33675#p114274)
to do this in the Linux for right time calcs
[change the clock](https://github.com/jcmvbkbc/linux-xtensa/blob/80c33fc984a4413670e096e662a9a4dec6119d59/arch/xtensa/boot/dts/esp32s3.dtsi#L32) to your wanted setup, in this case i point you to the wifi linux , 
if you use the previor version, its [here](https://github.com/jcmvbkbc/linux-xtensa/blob/65f7b38b91d5a39bb0ed44ed208c758daaad85e3/arch/xtensa/boot/dts/esp32s3.dts#L37)

also change the ESP System CPU speed in the menuconfig to your set of 80, 160 or 240 MHz
if you build the linux bootloader in ESP-IDF [linux 5.0.1 example](https://github.com/jcmvbkbc/esp-idf/tree/linux-5.0.1/examples/get-started/linux_boot) or [wifi version](https://github.com/jcmvbkbc/esp-hosted/tree/shmem/esp_hosted_ng/esp/esp_driver/network_adapter) , also you can change simple by edit the[ sdkconfig files](https://github.com/jcmvbkbc/esp-hosted/blob/d5e98ed61cd776bedf3dea5af45d9c58da8e58db/esp_hosted_ng/esp/esp_driver/network_adapter/sdkconfig.defaults.esp32s3#L288-L291) directly  


> Is possible to add SDCARD as media to boot kernel and rootfs with RW support ? 

add SD Support to your DTS, change the linux kernel code for load the driver, add your wanted filesystem support,  create an root Image for the SD Card, change the init.d to your need .... yes it is possible. feel free to chang any for your usecase :)


> Is possible to add I2C,SPI and GPIO's ?

[yes](https://twitter.com/eMbeddedHome/status/1663015901745012737)

you add the physicals to your DTS write Kernel Driver, add the init to the Kernelcode for load the Driver or Userspace APP
here is an DTS example that you get the idea

```
..
   			example-node {
        			compatible = "example,example-node";
        			text-property = "Hello World!";
    			};
..


```
 
test code snippet

```
...

    struct device_node *np;
    const char *text;
    int ret;
	int mycounts = 0;
	uint32_t pump; 

    np = of_find_node_by_name(NULL, "example-node");
    if (!np) {
        pr_err("Failed to find example node\n");
        return; //  -ENODEV;
    }

    ret = of_property_read_string(np, "text-property", &text);
    if (ret) {
        pr_err("Failed to read text property\n");
        of_node_put(np);
        return; // ret;
    }

    pr_info("Rudi was here: Text property: %s\n", text);

    of_node_put(np);

..
```

should bring you the "[hello world successfull driver load message](https://user-images.githubusercontent.com/16070445/241623175-e1255735-dcc1-42a7-9b4b-f9c3f76da964.png)"

you have then a working example with DTS and Kernel Driver Code
if you build a Userspace prog you can run it also from userspace


here is an example for the GPIO

dts expanded with gpio..
```

...

 		 gpio-controller@60004000 {
       			compatible = "gpio";
       			reg = <0x60004000 0x1000>;
       			gpio-controller;
       			#gpio-cells = <2>;
       			interrupt-controller;
       			#interrupt-cells = <2>;

...
};



```



simplest blinky in userspace :)


```
void myblinky (void) {

    mycounts = 0;

	// enable gpio
	(*((volatile uint32_t *) (0x60004000 + /*0xC*/ 0x20 ))) ^= 1 << 2;

	while(mycounts<10) {
	// w1ts
	(*((volatile uint32_t *) (0x60004000 + /*0x8*/ 0x24 ))) ^= 1 << 2;
	// to do: insert a pause
	printf("Blinky %d of 10\n", mycounts);	
	sleep(1);
	
    // w1tc
	(*((volatile uint32_t *) (0x60004000 + /*0xC*/ 0x28 ))) ^= 1 << 2;
	// to do: insert a pause
	sleep(1);
	mycounts++;
	}

	printf("World'S 1st Blinky on ESP32-S3 Linux Port done!\nrudi ;-)\n29. May 2023\n");
	printf("We controll now GPIO\nnext steps: I2C SPI... \n");
	printf("greetings fly out to friends all over the globe\n");

}
```


not tested or anything or right reg's, simplest that you get the idea for further things..

dts

```

/dts-v1/;
/plugin/;

/ {
    compatible = "espressif,esp32-s3", "espressif,esp32";
    fragment@0 {
        target = <&gpio>;
        __overlay__ {
            gpio_pins: gpio_pins {
                gpio0: gpio@0 {
                    compatible = "espressif,esp32s3-gpio";
                    reg = <0x60004000 0x0 0x4>;
                    label = "GPIO0";
                };
                gpio1: gpio@1 {
                    compatible = "espressif,esp32s3-gpio";
                    reg = <0x60004000 0x4 0x4>;
                    label = "GPIO1";
                };
                // specify more GPIO pins here ...
            };
        };
    };
};





```


kernel:

```

#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/types.h>

#include <linux/platform_device.h>
#include <linux/of.h>
#include <linux/of_device.h>
#include <linux/gpio/driver.h>

#define DRIVER_NAME "esp32-s3-gpio"
#define DRIVER_DESC "ESpressif GPIO Driver for ESP32-S3"

struct espressif_gpio {
    struct gpio_chip chip;
    void __iomem *regs;
};

static void espressif_gpio_set(struct gpio_chip *gc, unsigned offset, int value)
{
    struct espressif_gpio *egpio = container_of(gc, struct espressif_gpio, chip);
    u32 val;

    val = readl_relaxed(egpio->regs + (offset / 32) * 4);
    if (value)
        val |= 1 << (offset % 32);
    else
        val &= ~(1 << (offset % 32));
    writel_relaxed(val, egpio->regs + (offset / 32) * 4);
}

static int espressif_gpio_probe(struct platform_device *pdev)
{
    struct espressif_gpio *egpio;
    struct device_node *node = pdev->dev.of_node;
    int err;

    egpio = devm_kzalloc(&pdev->dev, sizeof(struct espressif_gpio), GFP_KERNEL);
    if (!egpio)
        return -ENOMEM;

    egpio->chip.parent = &pdev->dev;
    egpio->chip.base = 0;
    egpio->chip.ngpio = 32;
    egpio->chip.label = pdev->name;
    egpio->chip.direction_output = espressif_gpio_direction_output;
    egpio->chip.set = espressif_gpio_set;
    egpio->chip.get = espressif_gpio_get;

    egpio->regs = of_iomap(node, 0);
    if (!egpio->regs) {
        dev_err(&pdev->dev, "Failed to map registers\n");
        return -ENOMEM;
    }

    err = gpiochip_add_data(&egpio->chip, egpio);
    if (err) {
        dev_err(&pdev->dev, "Failed to add chip\n");
        return err;
    }

    dev_info(&pdev->dev, "Registered GPIO chip\n");
    return 0;
}

static int espressif_gpio_remove(struct platform_device *pdev)
{
    struct espressif_gpio *egpio = platform_get_drvdata(pdev);
    gpiochip_remove(&egpio->chip);
    iounmap(egpio->regs);
    return 0;
}

static const struct of_device_id espressif_gpio_of_matches[] = {
    { .compatible = "espressif,esp32s3-gpio", },
    {},
};
MODULE_DEVICE_TABLE(of, espressif_gpio_of_matches);

static struct platform_driver espressif_gpio_driver = {
    .driver = {
        .name = DRIVER_NAME,
        .owner = THIS_MODULE,
        .of_match_table = espressif_gpio_of_matches,
    },
    .probe = espressif_gpio_probe,
    .remove = espressif_gpio_remove,
};

static int __init espressif_gpio_init(void)
{
    return platform_driver_register(&espressif_gpio_driver);
}

static void __exit espressif_gpio_exit(void)
{
    platform_driver_unregister(&espressif_gpio_driver);
}

MODULE_LICENSE("GPL");
MODULE_AUTHOR(" ;-) ");
MODULE_DESCRIPTION(DRIVER_DESC);

module_init(espressif_gpio_init);
module_exit(espressif_gpio_exit);


```




> 
> Thank you, VS
hope this helps :)

you're welcome

**Comment by vslinuxdotnet** [comment]
> > Hello, I already compile and test it with wifi support, but I have some questions:
> > 
> 
> Hi - great so your wifi s3 linux is working :)
> 
> > Is possible to run Linux kernel with both CPU's ? 
> 
> without the wifi FreeRTOS on Wifi CPU ?
> in the wifi s3 linux we use all 2 CPU's
> run Linux and FreeRTOS  parallel cores which share some hardware (e.g. the interrupt matrix) 
> IDF code was (example) [expanded get some modifications](https://github.com/jcmvbkbc/esp-hosted/blob/d5e98ed61cd776bedf3dea5af45d9c58da8e58db/esp_hosted_ng/esp/esp_driver/network_adapter/main/shmem_slave_api.c#L45-L460).
> 
> Having SMP ? 
> - implementation of different IPI mechanism 
> - making IPI configurable.
> - ..
> 
> > Why CPU is running at 160mhz if 240mhz was available ?
> 
> cause it is set to 160 MHz usually as standard
> you can [change to 80 MHz as well and 240 MHz](https://esp32.com/viewtopic.php?f=17&t=33675#p114274)
> to do this in the Linux for right time calcs
> [change the clock](https://github.com/jcmvbkbc/linux-xtensa/blob/80c33fc984a4413670e096e662a9a4dec6119d59/arch/xtensa/boot/dts/esp32s3.dtsi#L32) to your wanted setup, in this case i point you to the wifi linux , 
> if you use the previor version, its [here](https://github.com/jcmvbkbc/linux-xtensa/blob/65f7b38b91d5a39bb0ed44ed208c758daaad85e3/arch/xtensa/boot/dts/esp32s3.dts#L37)
> 
> also change the ESP System CPU speed in the menuconfig to your set of 80, 160 or 240 MHz
> if you build the linux bootloader in ESP-IDF [linux 5.0.1 example](https://github.com/jcmvbkbc/esp-idf/tree/linux-5.0.1/examples/get-started/linux_boot) or [wifi version](https://github.com/jcmvbkbc/esp-hosted/tree/shmem/esp_hosted_ng/esp/esp_driver/network_adapter) , also you can change simple by edit the[ sdkconfig files](https://github.com/jcmvbkbc/esp-hosted/blob/d5e98ed61cd776bedf3dea5af45d9c58da8e58db/esp_hosted_ng/esp/esp_driver/network_adapter/sdkconfig.defaults.esp32s3#L288-L291) directly  
> 
> 
> > Is possible to add SDCARD as media to boot kernel and rootfs with RW support ? 
> 
> add SD Support to your DTS, change the linux kernel code for load the driver, add your wanted filesystem support,  create an root Image for the SD Card, change the init.d to your need .... yes it is possible. feel free to chang any for your usecase :)
> 
> 
> > Is possible to add I2C,SPI and GPIO's ?
> 
> [yes](https://twitter.com/eMbeddedHome/status/1663015901745012737)
> 
> you add the physicals to your DTS write Kernel Driver, add the init to the Kernelcode for load the Driver or Userspace APP
> here is an DTS example that you get the idea
> 
> ```
> ..
>    			example-node {
>         			compatible = "example,example-node";
>         			text-property = "Hello World!";
>     			};
> ..
> 
> 
> ```
>  
> test code snippet
> 
> ```
> ...
> 
>     struct device_node *np;
>     const char *text;
>     int ret;
> 	int mycounts = 0;
> 	uint32_t pump; 
> 
>     np = of_find_node_by_name(NULL, "example-node");
>     if (!np) {
>         pr_err("Failed to find example node\n");
>         return; //  -ENODEV;
>     }
> 
>     ret = of_property_read_string(np, "text-property", &text);
>     if (ret) {
>         pr_err("Failed to read text property\n");
>         of_node_put(np);
>         return; // ret;
>     }
> 
>     pr_info("Rudi was here: Text property: %s\n", text);
> 
>     of_node_put(np);
> 
> ..
> ```
> 
> should bring you the "[hello world successfull driver load message](https://user-images.githubusercontent.com/16070445/241623175-e1255735-dcc1-42a7-9b4b-f9c3f76da964.png)"
> 
> you have then a working example with DTS and Kernel Driver Code
> if you build a Userspace prog you can run it also from userspace
> 
> 
> here is an example for the GPIO
> 
> dts expanded with gpio..
> ```
> 
> ...
> 
>  		 gpio-controller@60004000 {
>        			compatible = "gpio";
>        			reg = <0x60004000 0x1000>;
>        			gpio-controller;
>        			#gpio-cells = <2>;
>        			interrupt-controller;
>        			#interrupt-cells = <2>;
> 
> ...
> };
> 
> 
> 
> ```
> 
> 
> 
> simplest blinky in userspace :)
> 
> 
> ```
> void myblinky (void) {
> 
>     mycounts = 0;
> 
> 	// enable gpio
> 	(*((volatile uint32_t *) (0x60004000 + /*0xC*/ 0x20 ))) ^= 1 << 2;
> 
> 	while(mycounts<10) {
> 	// w1ts
> 	(*((volatile uint32_t *) (0x60004000 + /*0x8*/ 0x24 ))) ^= 1 << 2;
> 	// to do: insert a pause
> 	printf("Blinky %d of 10\n", mycounts);	
> 	sleep(1);
> 	
>     // w1tc
> 	(*((volatile uint32_t *) (0x60004000 + /*0xC*/ 0x28 ))) ^= 1 << 2;
> 	// to do: insert a pause
> 	sleep(1);
> 	mycounts++;
> 	}
> 
> 	printf("World'S 1st Blinky on ESP32-S3 Linux Port done!\nrudi ;-)\n29. May 2023\n");
> 	printf("We controll now GPIO\nnext steps: I2C SPI... \n");
> 	printf("greetings fly out to friends all over the globe\n");
> 
> }
> ```
> 
> 
> not tested or anything or right reg's, simplest that you get the idea for further things..
> 
> dts
> 
> ```
> 
> /dts-v1/;
> /plugin/;
> 
> / {
>     compatible = "espressif,esp32-s3", "espressif,esp32";
>     fragment@0 {
>         target = <&gpio>;
>         __overlay__ {
>             gpio_pins: gpio_pins {
>                 gpio0: gpio@0 {
>                     compatible = "espressif,esp32s3-gpio";
>                     reg = <0x60004000 0x0 0x4>;
>                     label = "GPIO0";
>                 };
>                 gpio1: gpio@1 {
>                     compatible = "espressif,esp32s3-gpio";
>                     reg = <0x60004000 0x4 0x4>;
>                     label = "GPIO1";
>                 };
>                 // specify more GPIO pins here ...
>             };
>         };
>     };
> };
> 
> 
> 
> 
> 
> ```
> 
> 
> kernel:
> 
> ```
> 
> #include <linux/module.h>
> #include <linux/kernel.h>
> #include <linux/init.h>
> #include <linux/types.h>
> 
> #include <linux/platform_device.h>
> #include <linux/of.h>
> #include <linux/of_device.h>
> #include <linux/gpio/driver.h>
> 
> #define DRIVER_NAME "esp32-s3-gpio"
> #define DRIVER_DESC "ESpressif GPIO Driver for ESP32-S3"
> 
> struct espressif_gpio {
>     struct gpio_chip chip;
>     void __iomem *regs;
> };
> 
> static void espressif_gpio_set(struct gpio_chip *gc, unsigned offset, int value)
> {
>     struct espressif_gpio *egpio = container_of(gc, struct espressif_gpio, chip);
>     u32 val;
> 
>     val = readl_relaxed(egpio->regs + (offset / 32) * 4);
>     if (value)
>         val |= 1 << (offset % 32);
>     else
>         val &= ~(1 << (offset % 32));
>     writel_relaxed(val, egpio->regs + (offset / 32) * 4);
> }
> 
> static int espressif_gpio_probe(struct platform_device *pdev)
> {
>     struct espressif_gpio *egpio;
>     struct device_node *node = pdev->dev.of_node;
>     int err;
> 
>     egpio = devm_kzalloc(&pdev->dev, sizeof(struct espressif_gpio), GFP_KERNEL);
>     if (!egpio)
>         return -ENOMEM;
> 
>     egpio->chip.parent = &pdev->dev;
>     egpio->chip.base = 0;
>     egpio->chip.ngpio = 32;
>     egpio->chip.label = pdev->name;
>     egpio->chip.direction_output = espressif_gpio_direction_output;
>     egpio->chip.set = espressif_gpio_set;
>     egpio->chip.get = espressif_gpio_get;
> 
>     egpio->regs = of_iomap(node, 0);
>     if (!egpio->regs) {
>         dev_err(&pdev->dev, "Failed to map registers\n");
>         return -ENOMEM;
>     }
> 
>     err = gpiochip_add_data(&egpio->chip, egpio);
>     if (err) {
>         dev_err(&pdev->dev, "Failed to add chip\n");
>         return err;
>     }
> 
>     dev_info(&pdev->dev, "Registered GPIO chip\n");
>     return 0;
> }
> 
> static int espressif_gpio_remove(struct platform_device *pdev)
> {
>     struct espressif_gpio *egpio = platform_get_drvdata(pdev);
>     gpiochip_remove(&egpio->chip);
>     iounmap(egpio->regs);
>     return 0;
> }
> 
> static const struct of_device_id espressif_gpio_of_matches[] = {
>     { .compatible = "espressif,esp32s3-gpio", },
>     {},
> };
> MODULE_DEVICE_TABLE(of, espressif_gpio_of_matches);
> 
> static struct platform_driver espressif_gpio_driver = {
>     .driver = {
>         .name = DRIVER_NAME,
>         .owner = THIS_MODULE,
>         .of_match_table = espressif_gpio_of_matches,
>     },
>     .probe = espressif_gpio_probe,
>     .remove = espressif_gpio_remove,
> };
> 
> static int __init espressif_gpio_init(void)
> {
>     return platform_driver_register(&espressif_gpio_driver);
> }
> 
> static void __exit espressif_gpio_exit(void)
> {
>     platform_driver_unregister(&espressif_gpio_driver);
> }
> 
> MODULE_LICENSE("GPL");
> MODULE_AUTHOR(" ;-) ");
> MODULE_DESCRIPTION(DRIVER_DESC);
> 
> module_init(espressif_gpio_init);
> module_exit(espressif_gpio_exit);
> 
> 
> ```
> 
> 
> 
> 
> > 
> > Thank you, VS
> hope this helps :)
> 
> you're welcome
> 
> 


Hello,

Great job to answer my questions,
Two more :)

Where I change the partition from 8 MB to 16MB ?
Any script to rebuild the kernel and rootfs because the one that exists is to do the build, always get like 30G of data...

Thank you

VS

**Comment by ESP32DE** [comment]
Hi :)

> Where I change the partition from 8 MB to 16MB ? 

if you did not already change the flash size in the (ESP-IDF) [menuconfig](https://user-images.githubusercontent.com/16070445/246616223-c892d285-74c5-4076-81d9-5dcac53022a9.png) for your linux bootloader
you do this first there and config your used board to the physicals you use. 
Scroll down to the [ESP-IDF settings](https://github.com/ESP32DE/Boot-Linux-ESP32S3-Playground/tree/main/_start_here_/medial/howto)

Example a 16MB flash board you [set up then in menuconfig with this size](https://user-images.githubusercontent.com/16070445/246616389-393fff58-a4f9-42ee-93d3-574988fa4806.png)


Be sure you save your changes to `sdkconfig`


Before you build your new linux bootloader / binary partition table

You set the new size for your linux rootfs partition 
- in the [partition table](https://user-images.githubusercontent.com/16070445/246617841-2b8d718e-4e6c-4825-8b08-83303df5f42f.png) which you use in the ESP-IDF menuconfig settings
- in the [dts for the flash](https://github.com/jcmvbkbc/linux-xtensa/blob/65f7b38b91d5a39bb0ed44ed208c758daaad85e3/arch/xtensa/boot/dts/esp32s3.dts#L87-L101)
  - [flash total size ](https://github.com/jcmvbkbc/linux-xtensa/blob/65f7b38b91d5a39bb0ed44ed208c758daaad85e3/arch/xtensa/boot/dts/esp32s3.dts#L91)from 8 MB to 16   (0x00800000 -> 0x01000000 )
  - [rootfs partition](https://github.com/jcmvbkbc/linux-xtensa/blob/65f7b38b91d5a39bb0ed44ed208c758daaad85e3/arch/xtensa/boot/dts/esp32s3.dts#L100) example from 5 MB to 10 MB ( 0x00500000 -> 0x00A00000)

you build then the ESP-IDF linux bootloader app and get 3 files, 
- the 2nd stage Bootloader, 
- the binary partition table 
- and the Linux Bootloader App.

you flash this new setup then to your S3 Linux Board

the new rootfs with your extra space for your extra apps you build then over buildroot and flash the parts 
- linux kernel
- rootfs


> Any script to rebuild the kernel and rootfs because the one that exists is to do the build, always get like 30G of data...

only for completion, you know also the [newer script](https://gist.github.com/jcmvbkbc/316e6da728021c8ff670a24e674a35e6) which is for wifi ? the steps are near the same, just for wifi and a fresh install..

yes, you (re) build simple with buildroot "just only what you need"
be sure, you have exported XTENSA_GNU_CONFIG if you work on terminal / shell and do cross compile for your own apps to include it in the rootfs...

be sure you are in your right start folder, ( for [orientation and progress steps what we talk](https://gist.github.com/jcmvbkbc/316e6da728021c8ff670a24e674a35e6#file-rebuild-esp32s3-linux-wifi-sh-L38-L46) ) 

- linux kernel ( `linux-rebuild`), what looks like this: 
``nice make -C buildroot O=`pwd`/build-xtensa-2023.02-fdpic-esp32s3 linux-rebuild``

- rootfs (`rootfs-cramfs`) or what ever "image" you set up in the buildroot config,  what looks like this: 
``nice make -C buildroot O=`pwd`/build-xtensa-2023.02-fdpic-esp32s3 rootfs-cramfs``

specific things how to [handle buildroot](https://github.com/jcmvbkbc/buildroot/tree/xtensa-2023.02-fdpic/docs/manual)
specific things how to [handle crosstool-NG](https://crosstool-ng.github.io/docs/)

if you use the wifi s3 linux, you set up the new flash size first in wifi ESP-IDF app menuconfig, 
then the idf partition table from the [wifi app](https://github.com/jcmvbkbc/esp-hosted/tree/shmem/esp_hosted_ng/esp/esp_driver/network_adapter) there, and the dts(i) for the[ esp32-s3-wifi](https://github.com/jcmvbkbc/linux-xtensa/blob/xtensa-6.5-rc1-esp32wifi/arch/xtensa/boot/dts/esp32s3wifi.dts). 

JFYI: there is already a [16MB Partion Table](https://github.com/jcmvbkbc/esp-hosted/blob/shmem/esp_hosted_ng/esp/esp_driver/network_adapter/partition_table.esp32s3.16m) in the wifi app, just [change the dts(i) to the new 16MB Flash ](https://github.com/jcmvbkbc/linux-xtensa/blob/80c33fc984a4413670e096e662a9a4dec6119d59/arch/xtensa/boot/dts/esp32s3wifi.dts#L24-L37)size and your partition size for your rootfs like you need
how cool is that ( RTFM ) :) 

For future updates and changes you go in this projects you are working and set up the things. 
Flashsize ESP-IDF, partition table ESP-IDF, DTS(i) xtensa-linux.
 

hope this helps :)
#happyweekend nice #summerbreak23

**Comment by vslinuxdotnet** [comment]
Hello,
Seams that you need more ram :) I have this board: [core-esp32-s3-a10](https://pt.aliexpress.com/i/1005005145892791.html?gatewayAdapt=glo2bra) and have 16Mb flash, internal 8MB PSRAM, and space for external PSRAM on PCB, go to 16MB of RAM ? :P
Also the PCB have connections for sdcard, SPI and I2C.

In my opinion to make this project a little usable, if you add 150/200kb of flash space to user in jffs2 in RW, remove some in roofs, or for example or add SDCARD support for that?
Add a startup rc.local script in that partition to the user add the services or scripts.
This will permit to make something with the device because FS in ReadOnly.

Thanks,

VS

**Comment by ESP32DE** [comment]
Hi 

[jffs2](https://github.com/ESP32DE/Boot-Linux-ESP32S3-Playground/blob/main/history/Readme.md#05-june-2023) for the ro NOR-boot flash, rw NOR-partition,  for an extra rw, spi NAND.

sd card 2 and 4 line, eMMC, NAND,  is in the pipe. 

did you test wifi? 

best wishes
;-)

**Comment by ESP32DE** [comment]
@vslinuxdotnet 
guess :)

![image](https://github.com/ESP32DE/Boot-Linux-ESP32S3-Playground/assets/16070445/b010c0b6-3770-43ac-a827-159f67eb3666)

**Comment by markbirss** [comment]
good, nfsv3

**Comment by vslinuxdotnet** [comment]
> @vslinuxdotnet 
> guess :)
> 
> ![image](https://github.com/ESP32DE/Boot-Linux-ESP32S3-Playground/assets/16070445/b010c0b6-3770-43ac-a827-159f67eb3666)
> 
> 

Mounted, NFS partition.

**Comment by ESP32DE** [comment]
> > @vslinuxdotnet
> > guess :)

> Mounted, NFS partition.

yep :) 
JFYI:
[MTD tools](https://www.youtube.com/watch?v=l8fV5ScjRFw)..
[Lua](https://www.youtube.com/watch?v=m8AyipBql_o)
