### ISSUE TITLE
esp32s3 - unexpected maker S3 pro issue

### ISSUE THREAD

**Issue by vladbondarenko** [ESP32DE/Boot-Linux-ESP32S3-Playground#8]
Hello,

Is there any changes to be made to run linux on UM ProS3 board with 16MB flash? As i got a reboot loop:

![изображение](https://github.com/ESP32DE/Boot-Linux-ESP32S3-Playground/assets/9531461/2ab8e610-891c-4cd5-8081-fa92cc6aaa47)

Thanks!

**Comment by ESP32DE** [comment]
> Hello,
> 
> Is there any changes to be made to run linux on UM ProS3 board with 16MB flash? As i got a reboot loop:
> 
> 
> Thanks!

hi @vladbondarenko 
yes sure - why not?
did you self compile or what you did in your steps?

meanwhile:
test the hardware by this
[test this](https://github.com/ESP32DE/Boot-Linux-ESP32S3-Playground/blob/main/bins/S3/cores3n16R8qd.bin) - should work from the box, delete your flash before ( ful clean ) and if you need the fw, make a backup from your flash.
 
flash the downloaded bin to 0x0 and do not change the bin
should boot to the login, root@m5stack  
if not you need to check the board parameter and write it here then.

hope this helps, [have a note](https://twitter.com/eMbeddedHome/status/1689894673328844800) -- 
so if any can be slowly -  give a feedback how you get on - 
 
best wishes
;-)
