### ISSUE TITLE
Faild to login using putty

### ISSUE THREAD

**Issue by manobendro** [ESP32DE/Boot-Linux-ESP32S3-Playground#9]
I flash olimexS3WROOM_N8qdR8ot.bin rom on yd-esp32-s3-n16-r8 and putty for serial communication with the esp32 board. But I can't log into Linux with username root and password keeping empty. Can anyone tell me the root password or do I need to change the configuration on putty?

**Comment by ESP32DE** [comment]
> I flash olimexS3WROOM_N8qdR8ot.bin rom on yd-esp32-s3-n16-r8 and putty for serial communication with the esp32 board. But I can't log into Linux with username root and passanword keeping empty. Can anyone tell me the root password or do I need to change the configuration on putty?

Hi @manobendro 
https://github.com/ESP32DE/Boot-Linux-ESP32S3-Playground/issues/5#issuecomment-1660477445
best wishes
;-)

**Comment by manobendro** [comment]
Thanks
